name: Firebase Functions Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm ci
          npm i -g firebase-tools

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Deploy
        run: firebase deploy --token "$FIREBASE_TOKEN" --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
